import type { ProductType, Rarity } from '@kindstyle/database'

export const TYPE_MAP: Record<string, ProductType> = {
  'outfit': 'OUTFIT',
  'backbling': 'BACK_BLING',
  'pickaxe': 'PICKAXE',
  'glider': 'GLIDER',
  'emote': 'EMOTE',
  'wrap': 'WRAP',
  'music': 'MUSIC_PACK',
  'loadingscreen': 'LOADING_SCREEN',
  'spray': 'SPRAY',
  'contrail': 'CONTRAIL',
  'toy': 'TOY',
  'banner': 'BANNER',
  'bundle': 'BUNDLE',
  'pet': 'OTHER',
  'petcarrier': 'OTHER',
  'musicpack': 'MUSIC_PACK',
}

export const RARITY_MAP: Record<string, Rarity> = {
  'Common': 'COMMON',
  'Uncommon': 'UNCOMMON',
  'Rare': 'RARE',
  'Epic': 'EPIC',
  'Legendary': 'LEGENDARY',
  'Mythic': 'MYTHIC',
  'Exotic': 'EXOTIC',
  'IconSeries': 'ICON_SERIES',
  'StarWarsSeries': 'STAR_WARS',
  'DCSeries': 'DC',
  'MarvelSeries': 'MARVEL',
  'GamingLegends': 'GAMING_LEGENDS',
  'LavaSeries': 'LAVA',
  'FrozenSeries': 'FROZEN',
  'ShadowSeries': 'SHADOW',
  'SlurpSeries': 'SLURP',
  'DarkSeries': 'DARK',
  'Bright': 'BRIGHT',
  'BeyondSeries': 'BEYOND',
}

export const COLLECTION_MAP: Record<string, string> = {
  'Featured': 'Destacados',
  'Daily': 'Tienda del día',
  'Special': 'Especiales',
  'CreatorCode': 'Código de Creador',
  'MarvelSeries': 'Marvel',
  'DCSeries': 'DC Comics',
  'StarWarsSeries': 'Star Wars',
  'IconSeries': 'Icon Series',
  'GamingLegends': 'Gaming Legends',
}

export const PRODUCT_TYPE_LABELS: Record<ProductType, string> = {
  'OUTFIT': 'Outfits',
  'BACK_BLING': 'Back Bling',
  'PICKAXE': 'Picos',
  'GLIDER': 'Planeadores',
  'EMOTE': 'Emotes',
  'WRAP': 'Wraps',
  'MUSIC_PACK': 'Music Packs',
  'LOADING_SCREEN': 'Loading Screens',
  'SPRAY': 'Sprays',
  'CONTRAIL': 'Contrails',
  'TOY': 'Toys',
  'BANNER': 'Banners',
  'VBucks': 'V-Bucks',
  'BATTLE_PASS': 'Battle Pass',
  'CREW': 'Fortnite Crew',
  'BUNDLE': 'Bundles',
  'OTHER': 'Otros',
}
